### ISSUE TITLE
Bioconda package for VIBRANT

### ISSUE THREAD

**Issue by npavlovikj** [AnantharamanLab/VIBRANT#1]
Hi,

I am contributor to bioconda, and I would like to create a bioconda package for VIBRANT. In oder to do this, it would be great if you can tag an official release.
If you have any questions, please let me know.

Thank you,
Natasha

**Comment by npavlovikj** [comment]
Hi,

I went ahead and created a bioconda package for VIBRANT using the most recent commit, https://anaconda.org/bioconda/vibrant.
The recipe is in https://github.com/bioconda/bioconda-recipes/tree/6d0d514a035e15eeb231e958a2deb0929d768c78/recipes/vibrant.
The database is not downloaded as part of the package, but `post-link.sh` gives information to the user how to do that.

In order to install VIBRANT in an environment, e.g. vibrant, the following command should work:
`conda create -n vibrant -c conda-forge -c bioconda -c defaults vibrant=1.0.1`.
Next, the environment needs to be activated when VIBRANT is used, and deactivated afterwards:
```
conda activate vibrant
conda deactivate
```

I hope some of the VIBRANT users find this useful, and if you have any questions regarding the conda recipe, please let me know.

Thank you,
Natasha

**Comment by KrisKieft** [comment]
Hi Natasha,

Can the bioconda package be updated to reflect minor updates made to VIBRANT? Several bugs have been resolved and a `-folder` flag has been added. 

Thanks,
Kris

**Comment by npavlovikj** [comment]
Definitely! Can you please tag a release of the updated package?

Actually, bioconda has a pretty fancy bot that detects releases of newer versions. If you had a tagged release, in future, the bot can automatically update the version when you tag a new release.

**Comment by KrisKieft** [comment]
I tagged a new release, but I'm not super familiar with GitHub mechanics so I'm not sure if I did it correctly. I know that people are currently waiting for a bioconda update. Also, is there a need for a download-db.sh script to be ran separately? I built VIBRANT to be as streamline as possible and accessible to those who are less familiar with command line and script/conda locations. Thoughts on this?

Thanks

**Comment by npavlovikj** [comment]
Hi @KrisKieft ,

The tagged release look good - thank you for doing that!

I went ahead and updated the bioconda VIBRANT package with the tagged release, https://anaconda.org/bioconda/vibrant/files.

If one already has a conda environment with VIBRANT, the package can be updated with `conda update -n env vibrant, where `env` is the name of the existing environment.
If one wants to create and use new environment with VIBRANT, these are the steps:
```
$ conda create -n vibrant-1.0.1 -c conda-forge -c bioconda -c defaults vibrant=1.0.1=2
$ conda activate vibrant-1.0.1
$ download-db.sh
$ echo $VIBRANT_DATA_PATH
$ ls $VIBRANT_DATA_PATH
databases  files
$ VIBRANT_run.py -i <input_file>
$ conda deactivate
```

`download-db.sh` is run only once, to have the database files downloaded. This script is part of the system PATH, so no need to specify the absolute path to it as you have mentioned in the README. If the database files are downloaded elsewhere, one can set the variable VIBRANT_DATA_PATH to point to that location. Please note that VIBRANT_DATA_PATH should have the subdirectories "databases" and "files".

When someone installs VIBRANT from Github, beside the dependencies, the database needs to manually be downloaded with "VIBRANT_setup.py" and "VIBRANT_test_setup.py". `download-db.sh` does the exact same thing, https://github.com/bioconda/bioconda-recipes/blob/6d0d514a035e15eeb231e958a2deb0929d768c78/recipes/vibrant/download-db.sh - it is a wrapper to these two scripts. Thus, I personally think the bioconda package makes the installation and usage of VIBRANT easy and pretty streamlined.

I looked at issue #7, but without more information I can not replicate the issue. I don't think it is related to the package itself though, it looks more like missing VIBRANT_AMG* file that might have happened for various reasons. If you have the data to replicate this, I would be more than happy to take a look.

I tested the bioconda VIBRANT package with the example datasets and they worked fine. Please give the package a try, and let me know if you have any further questions or inquiries.

Thank you,
Best Regards,
Natasha

**Comment by KrisKieft** [comment]
Hi Natasha,

I tagged a new release of VIBRANT but do not see a corresponding update to the bioconda page. Is there a delay time on this? If it's not difficult I was wondering if the update could be pushed because I know some people are waiting for bioconda rather than GitHub. I tagged v1.2.0 as the latest release. Also, is it possible to add a flag to the `download-db.sh` script to specify where the databases are initially installed? This was a question I got from a user. Due to the edits made in the v1.2.0 release you may need to edit `download-db.sh`. 

Thanks,
Kris

**Comment by npavlovikj** [comment]
Hi Kris,

I think the Bot checks for new packages frequently, and it actually just updated the PR for 1.1.0 to 1.2.0, https://github.com/bioconda/bioconda-recipes/pull/20197. The 1.1.0 build failed, probably because the patch needs to be updated, but I haven't had time to look at it. If someone else doesn't do it, I will try to update it some this week. You can also give it a try yourself if you want.

Actually, the db download script, https://github.com/bioconda/bioconda-recipes/blob/7b8402e96e090045c11b3993ce52de6456f86360/recipes/vibrant/download-db.sh, has "echo "Downloading VIBRANT databases to ${VIBRANT_DATA_PATH}..."", which tells the user where the db files are downloaded. Also, once the package is installed, the user should see a note in the terminal saying "Please run download-db.sh to download all required VIBRANT database files to ${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/databases/". The variables above are substituted with the correct values. I guess I can add final line in the db download script that prints the path. Would that be ok?

Thank you,
Natasha

**Comment by npavlovikj** [comment]
Hi Kris,

Someone from the "bioconda" team fixed the failing PR, and now "vibrant" 1.2 is available as "bioconda" package as well.

Thank you,
Natasha

**Comment by KrisKieft** [comment]
Wonderful, thank you!

**Comment by KrisKieft** [comment]
Hi Natasha,

I noticed something on the [bioconda build](https://bioconda.github.io/recipes/vibrant/README.html) that is slightly off. It shows sci-kit learn as <= 0.21.3 but it should be >=. Can that be changed? Also, what did you mean by when you said:

> You can also give it a try yourself if you want.

Kris

**Comment by npavlovikj** [comment]
Hi Kris,

In the VIBRANT script you have:
```
if str(sklearn.__version__) != '0.21.3':
    if int(str(sklearn.__version__).split(".")[1]) > 21 or int(str(sklearn.__version__).split(".")[2]) > 3:
        note = 'CAUTION: running a version of Scikit-Learn higher than v0.21.3 may cause issues. With pip you can update by running "pip install --upgrade scikit-learn==0.21.3".'
    elif int(str(sklearn.__version__).split(".")[1]) < 21 or int(str(sklearn.__version__).split(".")[2]) < 3:
        note = 'CAUTION: running a version of Scikit-Learn lower than v0.21.3 will likely cause issues. With pip you can update by running "pip install --upgrade scikit-learn==0.21.3".'
if str(np.version.version) != '1.17.0':
    if int(str(np.version.version).split(".")[0]) < 1 or int(str(np.version.version).split(".")[1]) < 17:
        note = 'CAUTION: running a version of Numpy lower than v1.17.0 will likely cause issues. With pip you can update by running "pip install --upgrade numpy==1.17.0".'
```
so I was just following those instructions when specifying the dependencies.

When installing the package with conda, the highest compatible version of a dependency will be chosen. With `scikit-learn <=0.21.3`, `scikit-learn ==0.21.3` is actually used. With `scikit-learn >=0.21.3`, `scikit-learn ==0.22.1` will probably be used. Does this make sense? Do you still want a specific version to be used for `scikit-learn`?

Anyone can contribute to bioconda, and that is what I meant when I said that you can try modifying the recipe yourself. It is not hard, and there are detailed instructions provided here, https://bioconda.github.io/contributor/index.html. I am more than happy to update the VIBRANT recipe as time permits, but you can also check the instructions as well.

Thank you,
Natasha

**Comment by KrisKieft** [comment]
Yes, a specific version would be good. Scikit-Learn is sort of picky. It's using a machine learning model and likes to read the model from the same version that created the model. I created the model using v0.21.3. 

Kris

**Comment by Anto007** [comment]
I'm trying to run the conda version of VIBRANT but I get this error: "VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py."

The command-line I used after activation of the conda environment is below:
(/xxx/conda_vibrant_env) [xxx@xxx vibrant_test]$ VIBRANT_run.py -i sample_metagenome.fasta -t 24

**Comment by Anto007** [comment]
Here are the messages that I got after running the download-db script within the conda env:

(/xxx/conda_vibrant_env) [xxx@xxx vibrant_db]$ download-db.sh /xxx/vibrant_db
Set VIBRANT_DATA_PATH to /xxx/vibrant_db 
/xxx/conda_vibrant_env/bin/download-db.sh: line 17: /etc/conda/activate.d/vibrant.sh: No such file or directory
/xxx/conda_vibrant_env/bin/download-db.sh: line 21: /etc/conda/deactivate.d/vibrant.sh: No such file or directory
Downloading VIBRANT databases to /xxx/vibrant_db...

This script will download, extract subsets and press HMM profiles for VIBRANT.
This process will require ~20GB of temporary free storage space, but the final size requirement is ~11GB in the form of pressed HMM databases.
Please be patient. This only needs to be run once and will take a few minutes.
Logger started. Check log file for messages and errors.

VIBRANT v1.2.0 is good to go!
See example_data/ for quick test files.

Testing VIBRANT databases...
python: can't open file 'VIBRANT_test_setup.py': [Errno 2] No such file or directory
VIBRANT databases are downloaded successfully.

**Comment by Anto007** [comment]
The problem seems to be fixed now after I specified the exact path to the databases subdirectory by using the '-d' flag.

**Comment by KrisKieft** [comment]
It looks like the updated bioconda package may not be correct. The message you got that says `Logger started. Check log file for messages and errors` is specific to v1.2.0. There is no `VIBRANT_test_setup.py` in v1.2.0. Therefore something must have been updated incorrectly. I'll look into it.

Kris

**Comment by KrisKieft** [comment]
You actually might have gotten that error after everything was set up properly. Go ahead and run the example file to see if VIBRANT works correctly.

**Comment by Anto007** [comment]
Like I posted earlier: The problem seems to be fixed now after I specified the exact path to the databases subdirectory by using the '-d' flag. VIBRANT runs correctly for me; thanks!

**Comment by npavlovikj** [comment]
Looks like the "vibrant" recipe has been modified few days ago to include path for "download-db.sh" which is causing the issue @Anto007 observed. If you run "download-db.sh" without any path specified, the database files should be found just fine. 
"VIBRANT_test_setup.py" checks the downloaded databases, and it looks like it has been removed in the newest version of "vibrant", so that error message is harmless and it can be ignored until the recipe is fixed.

**Comment by Ahmed-Shibl** [comment]
Hello all, quick question please; I just want to confirm that running `conda update -n vibrant vibrant` will update my already-existing software (i.e. v1.2.0 to v1.2.1) in my already-existing conda environment called vibrant.  Or would I have to delete the environment and do a fresh installation?
Thanks!

**Comment by Ahmed-Shibl** [comment]
Hi all, I tried updating from v1.2.0 to v1.2.1 using `conda update -n vibrant vibrant` in the `vibrant` environment but still had the v1.2.0.

**Comment by KrisKieft** [comment]
Hi,

Please run `conda install -c bioconda vibrant==1.2.1` which should prompt you to overwrite v1.2.0.
