### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by SilasK** [AnantharamanLab/VIBRANT#10]
Dear Developpers, here just some personal feedback on the VIBRANT cli.

How you could make the CLI simpler for the users. 

I'm using version VIBRANT v1.0.1

Vibrant has a lot of options to specify the databases. 
Do you think this could be collapsed in one `--db` argument. 

Ideally the script `download-db.sh` should have 1 argument where to put all the databases. 

```

  -k K            path to KEGG HMMs (if moved from default location)
  -p P            path to Pfam HMMs (if moved from default location)
  -v V            path to VOG HMMs (if moved from default location)
  -e E            path to plasmid HMMs (if moved from default location)
  -a A            path to viral-subset Pfam HMMs (if moved from default location)
  -c C            path to VIBRANT categories file (if moved from default location)
  -n N            path to VIBRANT annotation to name file (if moved from default location)
  -s S            path to VIBRANT summary of KEGG metabolism file (if moved from default location)
  -m M            path to VIBRANT neural network machine learning model (if moved from default location)
  -g G            path to VIBRANT AMGs file (if moved from default location)

```

**Comment by KrisKieft** [comment]
Hi Silas,

You shouldn't need to specify these database locations. This is only if you move around the original parent directory. That said, I can look into collapsing them. As for the `download-db.sh` script, you shouldn't need to add any arguments. They download to a default location. This is what bioconda provided for VIBRANT and is not necessarily the most ideal procedure. VIBRANT was originally built for an easy git clone. I appreciate all questions/comments so please feel free to let me know if you have any other thoughts.

Kris

**Comment by SilasK** [comment]
Thank you for your quick response.
I don’t like default locations.
