### ISSUE TITLE
option to specify destination for database

### ISSUE THREAD

**Issue by snayfach** [AnantharamanLab/VIBRANT#13]
Would be nice to be able to run something like `download-db.sh --location=/path/to db`. Currently, I can't download the database because I don't have any disk space in the default download destination.

**Comment by KrisKieft** [comment]
I'll look into that. I have no control over the bioconda install so I'll have to contact a bioconda contributor. Alternatively you can download from GitHub and move the folder to the location that you want the databases downloaded. 

Kris
