### ISSUE TITLE
Prophage coordinates

### ISSUE THREAD

**Issue by snayfach** [AnantharamanLab/VIBRANT#14]
I can't seem to find genomic coordinates of prophages anywhere in the output files. Could you point me in the right direction?

**Comment by KrisKieft** [comment]
There are no coordinates generated in the output. In place of that, the sequences of excised prophages contain just the prophage region in the `VIBRANT_phages` folder. These will be sequences with "fragment" in the name. If you require coordinates then you'll have to reference the start of the first protein and the stop of the last protein. Start and stop locations can be found in the headers of the protein or gene files. All prophages are cut at protein sequences so those coordinates will reflect the excised genome. Hope that helps.

Kris

**Comment by snayfach** [comment]
Thanks, got it! You might consider adding a coordinates file for prophages in your next release
