### ISSUE TITLE
wget --no-hsts

### ISSUE THREAD

**Issue by aelbehery** [AnantharamanLab/VIBRANT#19]
I had an issue during database download and setup. Invoking `./VIBRANT_setup.py` threw an error `wget: unrecognized option '--no-hsts'`. My wget version is 1.14 and indeed it does not have a '--no-hsts' option. So, I had to remove this option from all wget commands from the VIBRANT_setup.py file and all worked just fine. I just wanted to tell you about it, so that you might want to modify the wget command in later VIBRANT versions to suit more versions of wget.

**Comment by KrisKieft** [comment]
Hi,

Thank you for bringing this to my attention. I have wget v1.20 and didn't realize this function was not supported by older versions. I removed the argument and it also works fine for me so I'll update the script accordingly. I actually plan on pushing a new update to VIBRANT and this can easily be implemented. 

Kris
