### ISSUE TITLE
How does VIBRANT handle 'N' bases in assembled scaffolds?

### ISSUE THREAD

**Issue by mshamash** [AnantharamanLab/VIBRANT#21]
Just wondering how VIBRANT handles N's in assembled DNA scaffolds from metaSPAdes. Would it be preferred to use contigs instead?

Thanks.

**Comment by KrisKieft** [comment]
Hi,

Great question. N's don't have much of an effect on VIBRANT besides not providing any information. VIBRANT does not rely at all on codon usage, tetranucleotide identity, gene density, protein size or other features that may be effected by individual or strings of N's (or X's in proteins). VIBRANT handles this however Prodigal (ORF prediction) handles N's and HMMER (hmmsearch, protein annotation) handles X's. Basically X's will just be masked ambiguities and may only lead to a couple unannotated proteins. The short answer is that scaffolds should be the best input. Hope that helps.

Kris

**Comment by mshamash** [comment]
Hi Kris,

Thanks for the information! I'll stick to scaffolds then since N's and X's won't affect much of the analysis.

I'll mark this as closed now.

Michael
