### ISSUE TITLE
.gff file of provirus position in scaffolds

### ISSUE THREAD

**Issue by dominikmerges** [AnantharamanLab/VIBRANT#30]
Hello,

is there positional information in VIRBANT output (i.e. BED/GFF/VCF file) where the fragments of pro viruses where extracted?
I would like to hard mask the virus sequence in the scaffold to explore the host sequence.

Many thanks and cheers,
Dominik

**Comment by thisisdomi** [comment]
Hi Kris,

great, many thanks! I will update my version.

Cheers,
Dominik

**Comment by niamhlacy** [comment]
Hello,

I am running version v1.2.1 however on complete genomes, however the VIBRANT_integrated_prophage_coordinates file isn't generated in the results folder. I was wondering if there is a reason for this or a problem with the installation? 

Thanks for taking the time to read this,
Niamh
