### ISSUE TITLE
VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.

### ISSUE THREAD

**Issue by bikramtemp** [AnantharamanLab/VIBRANT#35]
Getting below error every time I try to run any file from example_data folder
_VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py._

Please note below setup command was successful,

_python VIBRANT_setup.py -test

Verifying correct dependency versions ...
Logger started. Check log file for messages and errors.

VIBRANT v1.2.1 is good to go!
See example_data/ for quick test files._

I'm running it on macOS 11.0.1 with python 3.7 and all dependencies installed as per the mentioned steps.

**Comment by bikramtemp** [comment]
@KrisKieft 
Any help appreciated

**Comment by KrisKieft** [comment]
Hi,

I do not believe I have seen this issue before with a successful setup. There are two questions that I can ask to start with. (1) are there any error messages in the setup log file (see databases folder) or (2) do you see pressed HMM files in the databases folder? Pressed HMM files will end in .h3f, .h3i, .h3m and .h3p. It's likely that you downloaded the databases but they were unable to be pressed for some reason. If you do not see the pressed files then type in `hmmpress -h` and let me know if you get an error or a help message. If you do see the pressed files let me know and I'll try to figure out a different solution.

Kris

**Comment by bikramtemp** [comment]
Hi, 
Thanks for the quick reply, below are the answers

Q1:
Complete set of messages in the setup log file, no errors

> This script will download, extract subsets and press HMM profiles for VIBRANT.
This process will require ~20GB of temporary free storage space, but the final size requirement is ~11GB in the form of pressed HMM databases.
Please be patient. This only needs to be run once and will take a few minutes.

>Verifying Pfam, KEGG and VOG source websites are available for download ...

>Downloading HMM profiles for Pfam, KEGG and VOG from their source websites ...

>Unzipping profiles ...

>Concatenating individual profiles ...

>Extracting profiles used for VIBRANT ...

>Retrieved 19182 HMMs.

>Retrieved 10033 HMMs.

>Pressing profiles used for VIBRANT ...

>Done with databases. Several new databases are now in this folder.

>Verying correct dependency versions ...


>VIBRANT v1.2.1 is good to go!
See example_data/ for quick test files.

2. hmmpress-h command results in databases folder

<img width="527" alt="Screenshot 2020-12-15 at 10 54 30" src="https://user-images.githubusercontent.com/25223778/102199439-ee26d800-3ec3-11eb-9411-e6038b760df4.png">

And I can only see .h3i files in that folder and no file ending with h3p/h3m/h3f. Below are the only files in databases folder and after setup completed.

<img width="279" alt="Screenshot 2020-12-15 at 10 57 20" src="https://user-images.githubusercontent.com/25223778/102199793-51186f00-3ec4-11eb-8811-deff9735b2fa.png">

**Comment by KrisKieft** [comment]
It looks like we found the problem, we now need to figure out how to resolve it. Since there are no h3p/h3m/h3f files it means the databases were not pressed correctly/fully. My first guess is that your machine may have ran out of memory (RAM), but I'm not entirely sure. 

It's possible that we can finish the setup manually. First, remove the existing files ending in ".h3i" (just the 3 files). Retain all of the other .HMM files. Then, run the command `hmmpress KEGG_profiles_prokaryotes.HMM`. It's likely that you'll receive an error, but we need to know what that error is (pressing may take a couple minutes). 

The image below is the successful output for pressing the HMMs. If you get an error please let me know what it says. If you get a successful prompt then go ahead and run `hmmpress VOGDB94_phage.HMM` and `hmmpress Pfam-A_v32.HMM`. 

![image](https://user-images.githubusercontent.com/35313603/102243964-617b1a80-3ec1-11eb-95bb-3a71f2c4a9c2.png)

**Comment by bikramtemp** [comment]
Thank you very much.
Manual hmmpress on all .HMM files did the work, now all files are there and I'm able to run through example data.
Output is also OK.

Maybe some compatibility problem with different dependencies and this might be helpful to others who get such issue.

Thanks again and have a great festive season ahead.

**Comment by KrisKieft** [comment]
Wonderful, I'm happy to hear this worked. I'll dig a little deeper to see if this is a solvable issue to be implemented in a new version. Happy holidays.

**Comment by WDPLA** [comment]
Same problem, solved! Thanks to KrisKieft so much! By the way, to everyone with the same problem. Do not run "VIBRANT_setup.py" after running HMMPRESS, or those newly created files will be erased.

**Comment by lexikazen** [comment]
Here as well! HMMPRESS needs to be run on the KEGG, VOG, and PFAM HMM files and then it seems to be ok!

**Comment by Jlee795** [comment]
Hello, I did this and mine is not working. I am still getting the same error VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.

I'm not sure what to do to sort it
