### ISSUE TITLE
Missing prophage output

### ISSUE THREAD

**Issue by klangenf** [AnantharamanLab/VIBRANT#44]
I am running VIBRANT on virome samples with the "-virome" flag added to my runs. I have all of the expected output files except for the VIBRANT_integrated_prophage_coordinates_{sample}.tsv in the VIBRANT_results_{sample} folder. Is this an error in my run or a result of the "-virome" flag? Thank you!

**Comment by KrisKieft** [comment]
Hi,

Are you using the most recent v1.2.1? The coordinates file was a relatively recent addition.

Kris

**Comment by klangenf** [comment]
Yes, I recently installed VIBRANT v1.2.1.

**Comment by KrisKieft** [comment]
I'm actually not sure. The coordinates file should appear regardless of the `-virome` flag and regardless if prophages are identified. Is the coordinate file missing or is it present but empty? If there were any issues then an error would have been printed out.

**Comment by klangenf** [comment]
There is not an integrated prophage coordinates file. I noticed in the log file that the program says v1.2.0, but my installation says the current v1.2.1. Here is the log from my run: 
Command:  /home/{username}/anaconda3/envs/vibrant/bin/VIBRANT_run.py -i {sample_file}.fasta -t 4 -f nucl -folder VIBRANT-out -virome
Date:     2021-02-17
Start:    14:54:16
End:      21:02:19
Runtime:  368.1 minutes
Program:  VIBRANT v1.2.0

142142 scaffolds were read in.
61075 scaffolds met minimum requirements: at least 1000bp and 4 ORFs.
56172 putative phages were identified.

CAUTION: running a version of Scikit-Learn lower than v0.21.3 will likely cause issues. With pip you can update by running "pip install --upgrade scikit-learn==0.21.3".

**Comment by KrisKieft** [comment]
It looks like you're running v1.2.0, so that is why the coordinate file does not show up. If you do `/home/{username}/anaconda3/envs/vibrant/bin/VIBRANT_run.py --version` you should see v1.2.0. Try to update via conda (info in README). You should also update sklearn for the most accurate results.

Kris
