### ISSUE TITLE
KEGG database

### ISSUE THREAD

**Issue by sabina-llr** [AnantharamanLab/VIBRANT#50]
Hi,

I am trying to download and setup the 3 databases but, I keep getting this error:

--2021-06-15 16:24:06--  ftp://ftp.genome.jp/pub/db/kofam/archives/2019-08-10/profiles.tar.gz
  (try: 4) => ‘profiles.tar.gz’
Connecting to ftp.genome.jp (ftp.genome.jp)|133.103.200.25|:21... failed: Connection timed out.
Retrying.

Is there another way to install the Kofam db?

Thanks!

**Comment by KrisKieft** [comment]
Hi,

This is likely just a temporary internet or source website (source: KoFam) issue. Have you tried waiting a little while (>1 hour) and trying again? If this isn't resolved after 24 hours we can go over alternative routes.

**Comment by sabina-llr** [comment]
Thanks very much for your prompt reply.
I actually changed the KoFam ftp source link to the http link and the database download and setup worked!
