### ISSUE TITLE
problem of AMG number 

### ISSUE THREAD

**Issue by mujiezhang** [AnantharamanLab/VIBRANT#51]
Hello,
I got a question in VIBRANT results about AMG number. I found the number of AMG is 404 in VIBRANT_annotations_virus.tsv and VIBRANT_AMG_individuals_virus.tsv, but the number changed to 600 in VIBRANT_AMG_pathways_virus.tsv and the pdf of AMGs barplot. I wonder the reason for the difference.
Thanks.

**Comment by KrisKieft** [comment]
Hi,

This was an original oversight on my part for how KEGG parses their data. KEGG will allow individual KO numbers to be parts of multiple pathways if the protein/enzyme can have multiple functions, or if that function can be a part of multiple pathways. VIBRANT identified 404 AMGs but some of those AMGs can have multiple functions, or possible functions, that increase the pathway presence to 600.

**Comment by mujiezhang** [comment]
Really thanks for your helpful reply! I got it.

发送自 Windows 10 版邮件应用

发件人: Kris Kieft
发送时间: 2021年7月2日 23:39
收件人: AnantharamanLab/VIBRANT
抄送: mujiezhang; Author
主题: Re: [AnantharamanLab/VIBRANT] problem of AMG number (#51)

Hi,
This was an original oversight on my part for how KEGG parses their data. KEGG will allow individual KO numbers to be parts of multiple pathways if the protein/enzyme can have multiple functions, or if that function can be a part of multiple pathways. VIBRANT identified 404 AMGs but some of those AMGs can have multiple functions, or possible functions, that increase the pathway presence to 600.
