### ISSUE TITLE
Error in Integrated_phage_coordinates

### ISSUE THREAD

**Issue by JLammons14** [AnantharamanLab/VIBRANT#53]
I'm currently using version 1.2.1 to analyze metagenomic assembly data.  I completed my analysis on one sample and identified 17 phages from 720 contigs with run_vibrant.py. It looks like everything was generated as expected except the Intergrated_phaged_coordinates table is blank. I wasnt sure if this was an issue with the data I submitted or due to some other problem/mistake I may have made. I ran the mixed_example.fasta data and had the same problem, I'm not quite sure how to troubleshoot it  as the VIBRANT_log_run looks good and the VIBRANT_log_annotation_ file is blank, (although the annotation table is normal). I was hoping to have this file as I was planning on submitting this data to PropagAte after.

 Any help is appreciated, thanks for an awesome tool

**Comment by KrisKieft** [comment]
Hi,

This doesn't appear to be an issue but rather you don't have any integrated prophages. The mixed_example.fasta file does not have any either. You can verify this by searching for the term "/_fragment_" in your results. There should not be any.

**Comment by JLammons14** [comment]
Oof not sure how I missed the distinction between lytic and lysogenic in the results, regardless thanks for the quick response I really appreciate the help!
