### ISSUE TITLE
VIBRANT cannot setup in puthon 3.8?

### ISSUE THREAD

**Issue by ZhengXiaoxuan11542** [AnantharamanLab/VIBRANT#63]
Hi @KrisKieft,

thank you very much for creating such a brilliant instruction first!
I have run VIBRANT successfully on my old server as well as cyverse with nice results before. However, I cannot install the latest VIBRANT on my new server when I want to start my new work. I noticed that the VIBRANT relies on the package Scikit-learn ==0.21.3, which is now updated to version 1.1 and requires Python 3.8 ( which is my version) or newer. Will VIBRANT update the dependencies in the nearly future? Or do I just have to rebuild older Versions of Python to solve this problem?

Kind regards,
Xiaoxuan

**Comment by KrisKieft** [comment]
Hi,

The sklearn dependency will not be updated in the near future as that will require a full re-build of the machine learning model. Do you have conda installed? That can be a useful method to construct a virtual environment in which to install the older sklearn and Python versions. 

Kris

**Comment by ZhengXiaoxuan11542** [comment]
> Hi,
> 
> The sklearn dependency will not be updated in the near future as that will require a full re-build of the machine learning model. Do you have conda installed? That can be a useful method to construct a virtual environment in which to install the older sklearn and Python versions.
> 
> Kris

Hi Kris,
So glad to have your reply.
Construct an older python virtual environment is truly a good idea and now I have almost installed VIBRANT successfully in python 3.7. However, an error occurred when I tried to run the example data: 
`VIBRANT error: could not identify KEGG HMM files in database directory. Please run VIBRANT_setup.py.`
And I have run `python VIBRANT_setup.py -test` and get `VIBRANT v1.2.1 is good to go!
See example_data/ for quick test files.` in the log file. I tried to deal with it refering to [issue 35](https://github.com/AnantharamanLab/VIBRANT/issues/35#issue-766835911) but it didn`t work.

**Comment by ZhengXiaoxuan11542** [comment]
I solved this issue by givening the database address mannually by `-d`. So far the programming is running successfully.

**Comment by AndAvia** [comment]
> 我通过手动给出数据库地址解决了这个问题`-d`。至此编程运行成功。

老师，您好这个数据库地址代码应该怎样写，感谢您的回复！

**Comment by AndAvia** [comment]
> I solved this issue by givening the database address mannually by `-d`. So far the programming is running successfully.

老师您好，我设置数据库位置不成功，请问您是怎样设置的，这是我的代码及报错
VIBRANT_run.py -d ~/miniconda3/envs/VIBRANT/share/vibrant-1.2.0/databases

usage: VIBRANT_run.py [-h] [--version] -i I [-f {prot,nucl}] [-folder FOLDER]
                      [-t T] [-l L] [-o O] [-virome] [-no_plot] [-d D] [-m M]
VIBRANT_run.py: error: the following arguments are required: -i

**Comment by ZhengXiaoxuan11542** [comment]
> > 我通过手动给出数据库地址解决了这个问题`-d`。至此编程运行成功。
> 
> 老师您好，我设置数据库位置不成功，请问您是怎样设置的，这是我的代码及报错VIBRANT_run.py -d ~/ miniconda3/envs/VIBRANT/share/vibrant-1.2.0/databases
> 
> 用法：VIBRANT_run.py [-h] [--version] -i I [-f {prot,nucl}] [-folder FOLDER] [-t T] [-l L] [-o O] [-virome] [-no_plot] [-d D] [-m M] VIBRANT_run.py：错误：需要以下参数：-i

Hi, Just command the database location when you run your programme.  like `VIBRANT_run.py -t 25 -l 5000 -i ~/yourname.fa  -folder filter_location -d miniconda3/.../databases/`

**Comment by AndAvia** [comment]
> > > 我通过手动给出的数据库地址解决了这个问题`-d`。直到此编程运行成功。
> > 
> > 
> > 老师您好，我设置数据库位置不成功，请问您是怎样设置的，这是我的代码及报错VIBRANT_run.py -d ~/ miniconda3/envs/VIBRANT/share/vibrant-1.2.0/databases
> > 用法：VIBRANT_run.py [-h] [--version] -i I [-f {prot,nucl}] [-folder FOLDER] [-t T] [-l L] [-o O] [-virome] [-no_plot] [-d D] [-m M] VIBRANT_run.py：错误：需要以下参数：-i
> 
> 您好，只需在运行程序时命令数据库位置即可。喜欢`VIBRANT_run.py -t 25 -l 5000 -i ~/yourname.fa -folder filter_location -d miniconda3/.../databases/`

太感谢您了，运行成功了
