### ISSUE TITLE
Info: Regarding symlinks

### ISSUE THREAD

**Issue by susheelbhanu** [AnantharamanLab/VIBRANT#67]
Hi, 

I just tried to run `VIBRANT` on a set of metagenome assemblies that were `symlinked` from a different folder location. 

The log file showed that it could not find the fasta sequences. Re-running with a direct copy of the same file. 

Maybe this information could be added to `Notes` somewhere or simply left here for future reference.

Thank you,
Susheel

**Comment by KrisKieft** [comment]
Hi,

I've used symlinks before I haven't had any issues. Did you try `head -n 1 $file` or something from the current directory to verify that the link was set up properly for VIBRANT to find it? Let me know if the issue persists.

**Comment by susheelbhanu** [comment]
Hey Kris,

I was just about to close the issue. It so happened that the job ran out of memory. Sorry for the confusion!

I only realized this later 'cos vibrant kept running and snakemake was touching the files 🤷🏽‍♂️.

I can confirm now that the symlinks were not the issue.

Thanks for the prompt response!
