### ISSUE TITLE
Problem with gbk format

### ISSUE THREAD

**Issue by Leytoncito** [AnantharamanLab/VIBRANT#72]
When I run vibrant, everything works fine for me, however, the output gbk files are unusable by other programs.

I have tried several times to fix this problem, installing earlier versions of vibrant and installing vibrant on other computers, but the problem persists.

Perhaps it is due to an update of some dependency, I am not aware of this issue, but before I used vibrant without problems.

Also, I have tried to fix the gbk files manually, apparently it has a problem with tabs and/or spaces, hawever the problems persists.

**Comment by KrisKieft** [comment]
Hi,

I apologize but I probably will not get to fixing this issue. Please try other methods of building a genbank from the source genomes/proteins.

**Comment by MrTomRod** [comment]
@Leytoncito

I just had a similar problem (#71). However, as long as the `LOCUS` line is long enough, BioPython can read the format.

It occurred to me that this could be useful for you: you could write a simple Python script that [reads](http://biopython.org/DIST/docs/tutorial/Tutorial.html#sec13) the GenBank and [creates a new one](https://caretdashcaret.com/2016/06/15/how-to-create-genbank-files-with-biopython/), in the hope that BioPython creates more compatible output.

**Comment by Leytoncito** [comment]
Thaks @MrTomRod.

Besides Biopython, another way out is to simply re-annotate the predicted prophage sequence.
