### ISSUE TITLE
VIBRANT_AMG_pathways_* Total AMGs column

### ISSUE THREAD

**Issue by DeaconOfBiology** [AnantharamanLab/VIBRANT#79]
Sir/Ma'am,
I do not understand what the Total AMGs column is referring to. For example:
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/48442658/222024237-f84eb86d-e4c6-4492-9bba-91db7b3ad939.png">
on the first line it says that there are 4 total AMGs but their are only 2 listed in the Present AMG KOs column.

**Comment by KrisKieft** [comment]
Hi, you likely have a duplicate annotation. This often happens with K00558. So you have 4 AMGs but they only represent 2 unique KOs.

**Comment by DeaconOfBiology** [comment]
That makes sense. Thanks for the clarification and quick response.
