### ISSUE TITLE
ImportError: No module named 'numpy.random._pickle'

### ISSUE THREAD

**Issue by felipehcoutinho** [AnantharamanLab/VIBRANT#8]
Hello there, first, congratulations on the great tool! It seems really promising.

I have installed VIBRAT by downloading the latest version of the GitHub file. I downloaded the databases and run VIBRANT_test_setup.py and got the good to go message. But when I tried running VIBRANT on the example data (python3 ../VIBRANT_run.py -i mixed_example.fasta ) I got got the following errors:

Traceback (most recent call last):
  File "/home/rohit/felipe/VIBRANT-master/scripts/VIBRANT_annotation.py", line 1600, in <module>
    model = pickle.load(read_model)
ImportError: No module named 'numpy.random._pickle'

Also, It seems vibrant ran until the end but no sequences are classified as phages instead of the 4 that are indicated in your file. Here are the first 11 lines of the log file:

Command:  ../VIBRANT_run.py -i mixed_example.fasta
Date:     2019-12-10
Start:    15:25:51
End:      15:28:59
Runtime:  3.1 minutes
Program:  VIBRANT v1.0.1

10 scaffolds were read in.
7 scaffolds met minimum requirements: at least 1000bp and 4 ORFs.
0 putative phages were identified.

It seems something is wrong with either pickle or numpy. I have both installed (see below) so maybe it is an issue with the version? Any insights on how to fix this?

Below are my system specs:

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                144
On-line CPU(s) list:   0-143
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               1000.468
CPU max MHz:           2301,0000
CPU min MHz:           1000,0000
BogoMIPS:              4602.36
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              25344K
NUMA node0 CPU(s):     0-17,72-89
NUMA node1 CPU(s):     18-35,90-107
NUMA node2 CPU(s):     36-53,108-125
NUMA node3 CPU(s):     54-71,126-143

And this is the output of pip freeze:

apturl==0.5.2
asteval==0.9.13
awscli==1.16.133
backports.lzma==0.0.10
bcbio-gff==0.6.4
beautifulsoup4==4.4.1
biolib==0.0.46
biopython==1.66
blinker==1.3
botocore==1.12.123
Brlapi==0.6.4
chardet==2.3.0
checkbox-support==0.22
colorama==0.3.7
command-not-found==0.3
comparem==0.0.23
cryptography==1.2.3
cssselect==1.0.3
cycler==0.10.0
decorator==4.2.1
defer==1.0.6
DendroPy==4.4.0
docutils==0.14
feedparser==5.1.3
future==0.16.0
guacamole==0.9.2
helperlibs==0.1.9
html5lib==0.999
httplib2==0.9.1
idna==2.0
Jinja2==2.8
jmespath==0.9.3
language-selector==0.1
lmfit==0.9.13
louis==2.6.4
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
matplotlib==2.1.2
mcorr==20180506
mpld3==0.3
ncbi-genome-download==0.2.6
networkx==2.1
nose==1.3.7
numpy==1.11.0
oauthlib==1.0.3
onboard==1.2.0
padme==1.1.1
pandas==0.22.0
pexpect==4.0.1
pickle-mixin==1.0.2
Pillow==3.1.2
plainbox==0.25
protobuf==3.0.0b2
ptyprocess==0.5
pyasn1==0.1.9
pycups==1.9.73
pycurl==7.43.0
pyExcelerator==0.6.4.1
pygobject==3.20.0
PyJWT==1.3.0
pyparsing==2.0.3
pyquery==1.2.9
pysvg==0.2.2
python-apt==1.1.0b1+ubuntu0.16.4.1
python-dateutil==2.6.1
python-debian==0.1.27
python-systemd==231
pytz==2017.3
pyxdg==0.25
PyYAML==3.12
reportlab==3.3.0
requests==2.9.1
rpy2==2.9.2
rsa==3.4.2
s3transfer==0.2.0
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.9.0
sessioninstaller==0.0.0
six==1.12.0
ssh-import-id==5.5
system-service==0.3
tensorflow==0.10.0rc0
tqdm==4.31.1
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
uncertainties==3.0.3
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.13.1
usb-creator==0.3.0
virtualenv==15.0.1
xdiagnose==3.8.4.1
xkit==0.0.0
XlsxWriter==0.7.3

**Comment by KrisKieft** [comment]
Hi felipehcoutinho,

Quick answer: `pip install --upgrade numpy==1.17.0`

Thank you for using VIBRANT and I appreciate your interest! Fortunately this is an easy problem to solve because I have seen it before, and is my fault that I forgot to write the solution into the README. The required version of numpy is 1.17.0 and you are currently running 1.11.0 (thank you for the thorough specs/versions). I believe you can also use 1.16.0, but I would suggest the most recent update. You can solve this by running `pip install --upgrade numpy==1.17.0`. From there you should be good! Let me know if you need more help or have any other questions/comments. 

Kris

**Comment by felipehcoutinho** [comment]
Thank you so much for the speedy reply. This fixed te issue. Now I am getting the correct output but when running the program I get the following message:

/usr/local/lib/python3.5/dist-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.21.3 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator MLPClassifier from version 0.21.3 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

This seems related to what was said in issue #5 so Im assuming that everything is ok since it ran and gave the correct output?

**Comment by KrisKieft** [comment]
Hopefully this will also be an easy solution. I haven't seen this before but let's try updating scikit-learn. You are currently running v0.19.1. I've seen VIBRANT work well without errors using v0.20.4 and v0.21.3. I would suggest trying this first since the version was mentioned in the error: `pip install --upgrade scikit-learn==0.21.3`. I would assume that would also solve the issue of identifying 3 viruses instead of 4, but we'll see. Thank you for bringing these version issues to my attention. I can edit the README accordingly.

Kris

**Comment by felipehcoutinho** [comment]
That fixed the issue. I got the correct output with the example file and the program also ran smoothly with my own data. Many thanks!
