### ISSUE TITLE
-output flag?

### ISSUE THREAD

**Issue by rotoscan** [AnantharamanLab/VIBRANT#9]
Hello,

thank you for this very useful tool. I installed it and I intend to use it a lot in the research of our group. Currently, however, there is no "-output" flag and the output data is either being dumped in the same folder from the input (when executed locally) or in the home folder (when using a HPC cluster). Is there a work round to dump the output data on a folder of choice? If not, I think this would be a very nice feature for the next version of the tool.

Thanks a lot for the attention.

Kind Regards
Rodolfo

**Comment by KrisKieft** [comment]
Hi Rodolfo,

Great suggestion and an easy one to implement. I updated the "VIBRANT_run.py" script and there is now a "-folder" flag which will let you specify an output directory. The final folder will still be called "VIBRANT_" followed by the name of the input file, but the -folder flag will allow you to specify where that output folder will be deposited. If the directory specified by -folder does not exist then it will be created. To avoid re-downloading all the databases all you need to do is delete your old "VIBRANT_run.py" script and replace it with the new one. I hope that helps!

Kris

**Comment by rotoscan** [comment]
Hello Kris,

Thanks a lot for your swift reply and for adding this feature so promptly. Will put my hands on it asap.

Best Regards,
Rodolfo

**Comment by rotoscan** [comment]
Hello Kris,

I updated my VIBRANT and the -folder flag is working okay. Thanks!!

However, the intermediate files are still being dumped on the $HOME folder before being moved to the final folder defined on -folder. While this is not a critical issue, it could cause a problem depending on the name of the files. Specially when one has many runs at the same time.

If there would be a fix for that, I would be very grateful. When running many jobs concomitantly, the intermediary files can pile up and occupy too much space. Some HPC clusters have a limited quota on the $HOME folder and therefore this could be an issue.

Thanks again!
Best Regards
Rodolfo

**Comment by KrisKieft** [comment]
Hi Rodolfo,

Great point. I'm not used to running via HPC clusters so this is great to keep in mind. I pushed a new update which simply generates all the temp files within the specified `-folder` path. For this update you'll need to replace both the "VIBRANT_run.py" script as well as the "VIBRANT_annotation.py" script. There will be incompatibility in file locations if only one is replaced. I tested the update on my own system, but please let me know if you encounter any issues. For usage on shared systems (e.g., HPC clusters, lab or multi-lab servers) it is important to ensure that the location specified by `-folder` will not cause permissions errors when reading/writing/moving files in that location. Thanks for the great suggestion. 

Kris

**Comment by SilasK** [comment]
Hey Kris, 

I'm using the conda version of VIBRANT (VIBRANT v1.0.1). and expected the `-folder`option. It seems this is not yet released. 

Could you make a new release in your github directory? In theory, all the bioconda magic works automatically and your new version get's published. 

Do you wan't to call the argument `-folder`or `--folder`?

**Comment by KrisKieft** [comment]
Hi Silas,

I'm working on getting an update pushed to bioconda. Once you see the update show up on the bioconda package page (https://anaconda.org/bioconda/vibrant) you should have the -folder flag. Alternatively you can try a git clone. Hope that helps.

Kris

**Comment by rotoscan** [comment]
Hello Kris,

getting back to you regarding the newest update on the -folder flag. It is working flawlessly. Thanks a lot!!

Kind Regards
Rodolfo

**Comment by KrisKieft** [comment]
VIBRANT has been updated on bioconda. This should reflect the minor updates since v1.0.1 release. 

Information from a bioconda contributor (Natasha): 

If one already has a conda environment with VIBRANT, the package can be updated with conda update -n env vibrant, where env is the name of the existing environment.
If one wants to create and use new environment with VIBRANT, these are the steps:

$ conda create -n vibrant-1.0.1 -c conda-forge -c bioconda -c defaults vibrant=1.0.1=2
$ conda activate vibrant-1.0.1
$ download-db.sh
$ echo $VIBRANT_DATA_PATH
$ ls $VIBRANT_DATA_PATH
databases  files
$ VIBRANT_run.py -i <input_file>
$ conda deactivate
